name: Generator

on:
  issues:
    types: [opened, edited, labeled, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements #安装requests
      run: |
        pip install -r requirements.txt

    - name: Detect and Label Emails #检测订阅标签
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python friends/detect_and_label.py

    - name: Update links #更新
      run: |
        python friends/main.py
    - name: Commit & Push
      uses: action-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'output'
        force-push: 'true'
        commit-message: 'Generate Json'
        name: github-actions[bot]
        email: github-actions[bot]@noreply.github.com
